name: "Build & run on Ubuntu"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Build & run on Ubuntu
    runs-on: ubuntu-20.04

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: install Intel TBB
        run: sudo apt install libtbb-dev

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake ..
        working-directory: build_dir

      - name: build all checkpoints
        run: |
          cmake --build . --parallel 2 --target checkpoint_0 checkpoint_1 checkpoint_2 checkpoint_3 checkpoint_4 checkpoint_5 checkpoint_6 checkpoint_7
        working-directory: build_dir

      - name: run all checkpoints
        run: |
          ctest -VV --output-on-failure
        working-directory: build_dir
