name: "Build & run on Windows"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Build & run on Windows
    runs-on: windows-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure
        run: cmake ..
        working-directory: build_dir

      - name: build and run checkpoint_0
        run: |
          cmake --build . --parallel 2 --target checkpoint_0
#          .\checkpoint_0.exe
        working-directory: build_dir

      - name: build and run checkpoint_1
        run: |
          cmake --build . --parallel 2 --target checkpoint_1
#          .\checkpoint_1.exe
        working-directory: build_dir

      - name: build and run checkpoint_2
        run: |
          cmake --build . --parallel 2 --target checkpoint_2
#          .\checkpoint_2.exe
        working-directory: build_dir

      - name: build and run checkpoint_3
        run: |
          cmake --build . --parallel 2 --target checkpoint_3
#          .\checkpoint_3.exe
        working-directory: build_dir

      - name: build and run checkpoint_4
        run: |
          cmake --build . --parallel 2 --target checkpoint_4
#          .\checkpoint_4.exe
        working-directory: build_dir

      - name: build and run checkpoint_5
        run: |
          cmake --build . --parallel 2 --target checkpoint_5
#          .\checkpoint_5.exe
        working-directory: build_dir

      - name: build and run checkpoint_6
        run: |
          cmake --build . --parallel 2 --target checkpoint_6
#          .\checkpoint_6.exe
        working-directory: build_dir

      - name: build and run checkpoint_7
        run: |
          cmake --build . --parallel 2 --target checkpoint_7
#          .\checkpoint_7.exe
        working-directory: build_dir
